# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_discover_data_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover_data',
            name='switch',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
