# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20170928_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discover_data',
            new_name='DiscoverData',
        ),
    ]
